In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
ds=pd.read_csv('diabetes_new.csv')

In [3]:
ds.head()

Pregnancies  Glucose  BloodPressure  Insulin   BMI  Age  Outcome
0            6      148             72        0  33.6   50        1
1            1       85             66        0  26.6   31        0
2            8      183             64        0  23.3   32        1
3            1       89             66       94  28.1   21        0
4            0      137             40      168  43.1   33        1

In [4]:
ds.shape

(768, 7)

In [5]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'list[HashableT] | Callable[[Hashable], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Sequence[str] | Mapping[str, Sequence[str]] | None' = None,
    keep_default_na: 'bool' = True,
    n

In [6]:
ds.describe()

Pregnancies     Glucose  BloodPressure     Insulin         BMI  \
count   768.000000  768.000000     768.000000  768.000000  768.000000   
mean      3.845052  120.894531      69.105469   79.799479   31.992578   
std       3.369578   31.972618      19.355807  115.244002    7.884160   
min       0.000000    0.000000       0.000000    0.000000    0.000000   
25%       1.000000   99.000000      62.000000    0.000000   27.300000   
50%       3.000000  117.000000      72.000000   30.500000   32.000000   
75%       6.000000  140.250000      80.000000  127.250000   36.600000   
max      17.000000  199.000000     122.000000  846.000000   67.100000   

              Age     Outcome  
count  768.000000  768.000000  
mean    33.240885    0.348958  
std     11.760232    0.476951  
min     21.000000    0.000000  
25%     24.000000    0.000000  
50%     29.000000    0.000000  
75%     41.000000    1.000000  
max     81.000000    1.000000

In [7]:
ds['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [8]:
ds.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure     Insulin        BMI  \
Outcome                                                                  
0           3.298000  109.980000      68.184000   68.792000  30.304200   
1           4.865672  141.257463      70.824627  100.335821  35.142537   

               Age  
Outcome             
0        31.190000  
1        37.067164

In [9]:
#separating the data and labels

In [10]:
X = ds.drop(columns = 'Outcome', axis=1)
Y = ds['Outcome']

In [11]:
print(X)

     Pregnancies  Glucose  BloodPressure  Insulin   BMI  Age
0              6      148             72        0  33.6   50
1              1       85             66        0  26.6   31
2              8      183             64        0  23.3   32
3              1       89             66       94  28.1   21
4              0      137             40      168  43.1   33
..           ...      ...            ...      ...   ...  ...
763           10      101             76      180  32.9   63
764            2      122             70        0  36.8   27
765            5      121             72      112  26.2   30
766            1      126             60        0  30.1   47
767            1       93             70        0  30.4   23

[768 rows x 6 columns]


In [12]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [13]:
#data standardization

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X)

StandardScaler()

In [16]:
standardized_data = scaler.transform(X)

In [17]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 -0.69289057  0.20401277  1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 -0.69289057 -0.68442195 -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 -0.69289057 -1.10325546 -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075  0.27959377 -0.73518964 -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 -0.69289057 -0.24020459  1.17073215]
 [-0.84488505 -0.8730192   0.04624525 -0.69289057 -0.20212881 -0.87137393]]


In [18]:
X = standardized_data #represents the data
y = ds['Outcome'] #represents the model

In [19]:
print(X)
print(Y)

[[ 0.63994726  0.84832379  0.14964075 -0.69289057  0.20401277  1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 -0.69289057 -0.68442195 -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 -0.69289057 -1.10325546 -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075  0.27959377 -0.73518964 -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 -0.69289057 -0.24020459  1.17073215]
 [-0.84488505 -0.8730192   0.04624525 -0.69289057 -0.20212881 -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [20]:
#train test split

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2) 

In [22]:
print(X.shape, X_train.shape, X_test.shape)

(768, 6) (614, 6) (154, 6)


In [23]:
#training the model

In [24]:
classifier = svm.SVC(kernel='linear')

In [25]:
#training the sv machine classifier

In [26]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [27]:
#model evaluation

In [28]:
#accuracy score on the training data 

In [29]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [30]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.7736156351791531


In [31]:
#accuracy score on the testing data 

In [32]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [33]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.7597402597402597


In [34]:
#making a predictive system

In [47]:
input_data = (0,50,75,0,31.6,20)
#changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)
#reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
#standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)
if (prediction[0] == 0):
    print('You are not diabetic')
else:
    print('You are diabetic')

[[-1.14185152 -2.21879645  0.304734   -0.69289057 -0.04982572 -1.12663719]]
[0]
You are not diabetic


C:\Users\arpit\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [42]:
#saving the trained model

In [43]:
import pickle

In [44]:
pickle.dump(classifier, open('vsmodel.pkl', 'wb'))

In [45]:
#loading saved model
loaded_model = pickle.load(open('vsmodel.pkl', 'rb'))